### ISSUE TITLE
let과 var의 스코프

### ISSUE THREAD

**Issue by dongsik-yoo** [charmjeh/what_i_learned_today#2]
안녕하세요?^^
이슈 올려 주신 것 타고 오다 보니 공부하고 있는 내용이 있네요, 내용 중에 하나 알려드리면 좋을 것 같아서 이슈로 남깁니다.

https://github.com/charmjeh/what_i_learned_today/blob/b6b1af2b1deb4002333546971f31f8e5b93aebd4/%5Bjavascript%5D%20dom_event_onclick#L35

const, let은 말씀하신 것처럼 블록 스코프를 유효 범위로 가집니다.
var는 함수 스코프를 유효 범위로 가집니다. var로 선언했다고 하더라도 함수 스코프 내에서만 유효하기 때문에 전역이 유효 범위는 아니라고 할 수 있어요.

도움 되셨으면 좋겠습니다.^^
감사합니다.

**Comment by charmjeh** [comment]
그렇군요! ㅎㅎ 관심 가지고 조언 주셔서 정말 감사합니다. 
말씀주신 내용 잘 숙지하여 개발하도록 하겠습니다. ^^
